### ISSUE TITLE
Using headers only for "root" messages and introducing stamped types

### ISSUE THREAD

**Issue by cpupower** [bit-bots/humanoid_league_msgs#1]
Currently e.g. BallsInImage includes multiple BallInImage candiates. Each of these candidates has its own header field, and also BallsInImage has its own header. Probably instead of repeating the same header in one message, we should introduce BallInImageStamped and BallInImage messages separately. Publishers which only use BallInImage may then use BallInImageStamped, while BallsInImage includes the BallInImage message type without headers.

This may also apply to other message types.

**Comment by SammyRamone** [comment]
Hi,
thanks for filing this issue :)
I will take care of it next week.

**Comment by SammyRamone** [comment]
Hi again,
sorry for the long wait. I had to hand in my master thesis^^
I removed the headers from messages like BallInImage as you proposed, but I didn't add a ...Stamped message since BallsInImage with only one entry in the array is doing the same thing. 
Please tell me if this is okay now. Then I will close the issue
Thank you again for your contribution :)

**Comment by SammyRamone** [comment]
Since there are no further complains, I will close the issue
